# Generated by Django 3.2.16 on 2024-04-14 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recherche_formateurs', '0002_auto_20240414_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secteur',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to='recherche_formateurs.region'),
        ),
    ]
