# Generated by Django 3.2.16 on 2024-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche_formateurs', '0003_alter_secteur_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='secteur',
            name='region',
        ),
        migrations.AddField(
            model_name='formateur',
            name='domaines',
            field=models.ManyToManyField(related_name='formateurs', to='recherche_formateurs.Domaine'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='secteurs',
            field=models.ManyToManyField(related_name='formateurs', to='recherche_formateurs.Secteur'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
