# Generated by Django 3.2.16 on 2024-04-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche_formateurs', '0004_auto_20240414_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='commentaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
