# Generated by Django 3.2.16 on 2024-04-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche_formateurs', '0005_auto_20240415_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='national',
            field=models.BooleanField(default=False),
        ),
    ]
