# Generated by Django 3.2.16 on 2024-04-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recherche_formateurs', '0007_alter_formateur_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secteur',
            options={'ordering': ['code_postal']},
        ),
    ]
