# Generated by Django 3.2.16 on 2024-04-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche_formateurs', '0008_alter_secteur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
