# Generated by Django 3.2.16 on 2024-04-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche_formateurs', '0009_alter_formateur_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
